dist: trusty
sudo: required
language: java
install: true
script:
  # the total output is approx. 50k lines, so we need to filter it a bit
  - mvn test | grep "^\\[" | tee mvn.log
  # test if the output of the mvn command contained an "[INFO] BUILD SUCCESS" entry
  - tail mvn.log
  - grep "\[INFO\] BUILD SUCCESS" mvn.log
  - grep "BUILD SUCCESS" mvn.log
notifications:
  slack: ldbcouncil:0FIBC03v0bz1jQqtoYsLRE1h
  email: false
  on_success: change
  on_failure: always
